extends Node2D

func _ready():
	$Camera2D.make_current()
	$TimeMachine.can_use = false

func _on_PlayButton_pressed():
	$Transit.change_scene("res://levels/Level_One.tscn", 0.5, 0.2)

func _on_PlayButton_mouse_entered():
	$VBoxContainer/HBoxContainer/TextureRect/PlayButton/selected.visible = true
	$VBoxContainer/HBoxContainer/TextureRect/LoadButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/SettingsButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/ExitButton/selected.visible = false

func _on_LoadButton_pressed():
	$TimeMachine.continue_game()

func _on_LoadButton_mouse_entered():
	$VBoxContainer/HBoxContainer/TextureRect/PlayButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/LoadButton/selected.visible = true
	$VBoxContainer/HBoxContainer/TextureRect/SettingsButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/ExitButton/selected.visible = false

func _on_SettingsButton_pressed():
	pass 

func _on_SettingsButton_mouse_entered():
	$VBoxContainer/HBoxContainer/TextureRect/PlayButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/LoadButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/SettingsButton/selected.visible = true
	$VBoxContainer/HBoxContainer/TextureRect/ExitButton/selected.visible = false

func _on_ExitButton_pressed():
	get_tree().quit()

func _on_ExitButton_mouse_entered():
	$VBoxContainer/HBoxContainer/TextureRect/PlayButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/LoadButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/SettingsButton/selected.visible = false
	$VBoxContainer/HBoxContainer/TextureRect/ExitButton/selected.visible = true

